# Generated by Django 3.2.25 on 2025-03-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('client', models.CharField(max_length=100, verbose_name='العميل')),
                ('location', models.CharField(max_length=100, verbose_name='الموقع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('completed', 'مكتمل'), ('in_progress', 'قيد التنفيذ'), ('planned', 'مخطط له')], max_length=20, verbose_name='الحالة')),
                ('short_description', models.TextField(verbose_name='وصف مختصر')),
                ('description', models.TextField(verbose_name='الوصف التفصيلي')),
                ('main_image', models.ImageField(upload_to='projects/', verbose_name='الصورة الرئيسية')),
                ('featured', models.BooleanField(default=False, verbose_name='مميز')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('short_description', models.TextField(verbose_name='وصف مختصر')),
                ('description', models.TextField(verbose_name='الوصف التفصيلي')),
                ('main_image', models.ImageField(upload_to='services/', verbose_name='الصورة الرئيسية')),
                ('icon', models.CharField(help_text='اسم أيقونة من Font Awesome', max_length=50, verbose_name='أيقونة')),
                ('featured', models.BooleanField(default=False, verbose_name='مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(help_text='اسم أيقونة من Font Awesome', max_length=50, verbose_name='أيقونة')),
            ],
            options={
                'verbose_name': 'فئة خدمات',
                'verbose_name_plural': 'فئات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='الصورة')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='العنوان')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'صورة الخدمة',
                'verbose_name_plural': 'صور الخدمات',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='الصورة')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='العنوان')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.project')),
            ],
            options={
                'verbose_name': 'صورة المشروع',
                'verbose_name_plural': 'صور المشاريع',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='projects', to='services.Service', verbose_name='الخدمات المرتبطة'),
        ),
    ]
